#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Apr 29 13:53:55 CEST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 2ba28e1c2ba94d8da805417a87629514 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot self_test_system_behav xil_defaultlib.self_test_system -log elaborate.log"
xelab -wto 2ba28e1c2ba94d8da805417a87629514 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot self_test_system_behav xil_defaultlib.self_test_system -log elaborate.log

