webtalk_init -webtalk_dir /uio/hume/student-u81/rolfvh/IN3160-22/oblig6/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/self_test_system_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 31 21:05:01 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174112965_174112966_210753894_743" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "58b05137-9907-440a-b997-fbe5107ac083" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ec67b883a27e4d71a1ee579c317843fb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "RedHatEnterprise" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Red Hat Enterprise Linux release 8.5 (Ootpa)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1995.312 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "24" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125556_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4122979874 -regid "174112965_174112966_210753894_743" -xml /uio/hume/student-u81/rolfvh/IN3160-22/oblig6/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/self_test_system_behav/webtalk/usage_statistics_ext_xsim.xml -html /uio/hume/student-u81/rolfvh/IN3160-22/oblig6/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/self_test_system_behav/webtalk/usage_statistics_ext_xsim.html -wdm /uio/hume/student-u81/rolfvh/IN3160-22/oblig6/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/self_test_system_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
