#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Feb 18 20:44:03 CET 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto fd41472625fe4a3eb5d99fed49f4c695 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_pargen_behav xil_defaultlib.tb_pargen -log elaborate.log"
xelab -wto fd41472625fe4a3eb5d99fed49f4c695 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_pargen_behav xil_defaultlib.tb_pargen -log elaborate.log

