
####################################################################################
# Generated by Vivado 2020.2 built on 'Wed Nov 18 09:12:47 MST 2020' by 'xbuild'
# Command Used: write_xdc -force /uio/hume/student-u81/rolfvh/in3160-new/oblig1/vivado_counter/constrs_1.xdc
####################################################################################


####################################################################################
# Constraints from file : 'my_constraints.xdc'
####################################################################################

set_property PACKAGE_PIN H17 [get_ports up]


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
