# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/oblig8/constaints.xdc

# Block Designs: bd/tutorial_bd/tutorial_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tutorial_bd || ORIG_REF_NAME==tutorial_bd} -quiet] -quiet

# IP: bd/tutorial_bd/ip/tutorial_bd_processing_system7_0_0/tutorial_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tutorial_bd_processing_system7_0_0 || ORIG_REF_NAME==tutorial_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/tutorial_bd/ip/tutorial_bd_axi_gpio_0_0/tutorial_bd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tutorial_bd_axi_gpio_0_0 || ORIG_REF_NAME==tutorial_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/tutorial_bd/ip/tutorial_bd_auto_pc_0/tutorial_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tutorial_bd_auto_pc_0 || ORIG_REF_NAME==tutorial_bd_auto_pc_0} -quiet] -quiet

# IP: bd/tutorial_bd/ip/tutorial_bd_ps7_0_axi_periph_0/tutorial_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tutorial_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==tutorial_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/tutorial_bd/ip/tutorial_bd_rst_ps7_0_100M_0/tutorial_bd_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tutorial_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==tutorial_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/tutorial_bd/ip/tutorial_bd_fpga_system_0_0/tutorial_bd_fpga_system_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tutorial_bd_fpga_system_0_0 || ORIG_REF_NAME==tutorial_bd_fpga_system_0_0} -quiet] -quiet

# XDC: /uio/hume/student-u81/rolfvh/IN3160-22/oblig10/oblig_10_system/oblig_10_system.gen/sources_1/bd/tutorial_bd/tutorial_bd_ooc.xdc
