#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Jan 31 11:46:40 CET 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto bd502475279e4caf82e12f4534827ce2 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot TEST_FIRST_behav xil_defaultlib.TEST_FIRST -log elaborate.log"
xelab -wto bd502475279e4caf82e12f4534827ce2 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot TEST_FIRST_behav xil_defaultlib.TEST_FIRST -log elaborate.log

